# Generated by Django 4.2.2 on 2024-02-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_title', models.CharField(max_length=255)),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
    ]
