# Generated by Django 4.2.2 on 2024-02-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWithDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='layer_thickness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_thickness_category', models.IntegerField()),
                ('layer_thickness_vendor_code', models.CharField(max_length=128)),
                ('layer_thickness_thickness', models.FloatField()),
            ],
        ),
    ]
